# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHbnfYMjqLc6CpmXj9D7rrdQrJedZCm0
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("Handwashing Saves Lives")
st.write(
    "This visualization shows the historical data on births and deaths in two clinics, "
    "highlighting how the introduction of handwashing affected mortality rates."
)

file = st.file_uploader("Upload the yearly_deaths_by_clinic.csv file", type="csv")

if file is not None:
    df = pd.read_csv(file)

    st.subheader("Raw Data Preview")
    st.dataframe(df)

    # Column names from your file
    year_col = "Year"
    births_col = "Birth"
    deaths_col = "Deaths"
    clinic_col = "Clinic"

    # Filter by clinic
    clinics = sorted(df[clinic_col].unique())
    selected_clinic = st.selectbox("Select a clinic", clinics)
    df_filtered = df[df[clinic_col] == selected_clinic]

    # Filter by year range
    st.subheader("Filters")
    years = sorted(df_filtered[year_col].unique())
    year_range = st.slider(
        "Select Year Range",
        min_value=int(min(years)),
        max_value=int(max(years)),
        value=(int(min(years)), int(max(years)))
    )
    df_filtered = df_filtered[
        (df_filtered[year_col] >= year_range[0]) &
        (df_filtered[year_col] <= year_range[1])
    ]

    # Line Chart: Deaths Over Time
    st.subheader("Deaths Over Time")
    fig, ax = plt.subplots()
    ax.plot(df_filtered[year_col], df_filtered[deaths_col])
    ax.set_xlabel("Year")
    ax.set_ylabel("Deaths")
    st.pyplot(fig)

    # Bar Chart: Births vs Deaths
    st.subheader("Births vs Deaths")
    fig2, ax2 = plt.subplots()
    ax2.bar(df_filtered[year_col], df_filtered[births_col], label="Births")
    ax2.bar(df_filtered[year_col], df_filtered[deaths_col], label="Deaths")
    ax2.set_xlabel("Year")
    ax2.set_ylabel("Count")
    ax2.legend()
    st.pyplot(fig2)

    st.subheader("Summary of Findings")
    st.write(
        "Deaths decline after handwashing is introduced, especially in Clinic 1. "
        "Comparing births and deaths over time shows how the mortality rate dropped as hygiene improved. "
        "This pattern supports the idea that handwashing played a key role in saving lives."
    )

else:
    st.info("Upload your CSV to continue.")